import type { ParameterDefinition } from './parameters'
import type { SynthPreset } from './profiles'

export const webSynthParameters = [
  { id: 'osc1Wave', section: 'Oscillator 1', label: 'Oscillator 1 waveform', shortLabel: 'Wave', min: 0, max: 3, defaultValue: 2, valueLabels: ['Sine', 'Triangle', 'Sawtooth', 'Square'] },
  { id: 'osc1Detune', section: 'Oscillator 1', label: 'Oscillator 1 detune', shortLabel: 'Detune', min: -100, max: 100, defaultValue: 0, displayOffset: 0 },
  { id: 'osc2Wave', section: 'Oscillator 2', label: 'Oscillator 2 waveform', shortLabel: 'Wave', min: 0, max: 3, defaultValue: 2, valueLabels: ['Sine', 'Triangle', 'Sawtooth', 'Square'] },
  { id: 'osc2Detune', section: 'Oscillator 2', label: 'Oscillator 2 detune', shortLabel: 'Detune', min: -100, max: 100, defaultValue: 7, displayOffset: 0 },
  { id: 'filterCutoff', section: 'Filter', label: 'Filter cutoff', shortLabel: 'Cutoff', min: 100, max: 12000, defaultValue: 6000 },
  { id: 'filterResonance', section: 'Filter', label: 'Filter resonance', shortLabel: 'Resonance', min: 0, max: 100, defaultValue: 15 },
  { id: 'filterEnvelopeAmount', section: 'Filter', label: 'Filter envelope amount', shortLabel: 'Envelope amount', min: 0, max: 100, defaultValue: 35 },
  { id: 'ampAttack', section: 'Amp envelope', label: 'Amplifier attack', shortLabel: 'Attack', min: 0, max: 5000, defaultValue: 15 },
  { id: 'ampDecay', section: 'Amp envelope', label: 'Amplifier decay', shortLabel: 'Decay', min: 0, max: 5000, defaultValue: 350 },
  { id: 'ampSustain', section: 'Amp envelope', label: 'Amplifier sustain', shortLabel: 'Sustain', min: 0, max: 100, defaultValue: 75 },
  { id: 'ampRelease', section: 'Amp envelope', label: 'Amplifier release', shortLabel: 'Release', min: 0, max: 8000, defaultValue: 500 },
  { id: 'filterAttack', section: 'Filter envelope', label: 'Filter attack', shortLabel: 'Attack', min: 0, max: 5000, defaultValue: 10 },
  { id: 'filterDecay', section: 'Filter envelope', label: 'Filter decay', shortLabel: 'Decay', min: 0, max: 5000, defaultValue: 600 },
  { id: 'filterSustain', section: 'Filter envelope', label: 'Filter sustain', shortLabel: 'Sustain', min: 0, max: 100, defaultValue: 30 },
  { id: 'filterRelease', section: 'Filter envelope', label: 'Filter release', shortLabel: 'Release', min: 0, max: 8000, defaultValue: 500 },
  { id: 'lfoRate', section: 'LFO', label: 'LFO rate', shortLabel: 'Rate', min: 1, max: 20, defaultValue: 4 },
  { id: 'lfoPitchDepth', section: 'LFO', label: 'LFO pitch depth', shortLabel: 'Pitch depth', min: 0, max: 1200, defaultValue: 0 },
  { id: 'lfoFilterDepth', section: 'LFO', label: 'LFO filter depth', shortLabel: 'Filter depth', min: 0, max: 100, defaultValue: 0 },
] as const satisfies readonly ParameterDefinition[]

export type WebSynthParameterId = (typeof webSynthParameters)[number]['id']

export const webSynthDefaultValues = Object.fromEntries(
  webSynthParameters.map((parameter) => [parameter.id, parameter.defaultValue]),
) as Record<WebSynthParameterId, number>

export const webSynthPresets = [
  {
    id: 'soft-pad',
    name: 'Soft Pad',
    values: {
      ...webSynthDefaultValues,
      osc1Wave: 1,
      osc2Wave: 2,
      osc2Detune: 12,
      filterCutoff: 3200,
      filterResonance: 20,
      filterEnvelopeAmount: 25,
      ampAttack: 900,
      ampDecay: 1200,
      ampSustain: 68,
      ampRelease: 1800,
      filterAttack: 700,
      filterDecay: 1400,
      filterSustain: 35,
      filterRelease: 1700,
      lfoRate: 3,
      lfoPitchDepth: 7,
      lfoFilterDepth: 12,
    },
  },
  {
    id: 'bright-lead',
    name: 'Bright Lead',
    values: {
      ...webSynthDefaultValues,
      osc1Wave: 2,
      osc2Wave: 3,
      osc2Detune: 5,
      filterCutoff: 7200,
      filterResonance: 32,
      filterEnvelopeAmount: 55,
      ampAttack: 5,
      ampDecay: 500,
      ampSustain: 80,
      ampRelease: 250,
      filterAttack: 0,
      filterDecay: 420,
      filterSustain: 28,
      filterRelease: 240,
      lfoRate: 6,
      lfoPitchDepth: 4,
      lfoFilterDepth: 8,
    },
  },
  {
    id: 'round-bass',
    name: 'Round Bass',
    values: {
      ...webSynthDefaultValues,
      osc1Wave: 2,
      osc2Wave: 0,
      osc2Detune: -12,
      filterCutoff: 950,
      filterResonance: 18,
      filterEnvelopeAmount: 72,
      ampAttack: 3,
      ampDecay: 280,
      ampSustain: 82,
      ampRelease: 160,
      filterAttack: 0,
      filterDecay: 330,
      filterSustain: 8,
      filterRelease: 150,
      lfoRate: 2,
      lfoPitchDepth: 0,
      lfoFilterDepth: 4,
    },
  },
] as const satisfies readonly SynthPreset[]
