import type { ParameterDefinition } from './parameters'
import type { SynthPreset } from './profiles'

export const webSynthParameters = [
  { id: 'osc1Wave', section: 'Oscillator 1', label: 'Oscillator 1 waveform', shortLabel: 'Wave', min: 0, max: 3, defaultValue: 2, valueLabels: ['Sine', 'Triangle', 'Sawtooth', 'Square'] },
  { id: 'osc1Detune', section: 'Oscillator 1', label: 'Oscillator 1 detune', shortLabel: 'Detune', min: -100, max: 100, defaultValue: 0, displayOffset: 0 },
  { id: 'osc1Shape', section: 'Oscillator 1', label: 'Oscillator 1 shape', shortLabel: 'Shape', min: 1, max: 99, defaultValue: 50 },
  { id: 'osc1Level', section: 'Mixer', label: 'Oscillator 1 level', shortLabel: 'Osc 1', min: 0, max: 100, defaultValue: 100 },
  { id: 'osc2Wave', section: 'Oscillator 2', label: 'Oscillator 2 waveform', shortLabel: 'Wave', min: 0, max: 3, defaultValue: 2, valueLabels: ['Sine', 'Triangle', 'Sawtooth', 'Square'] },
  { id: 'osc2Detune', section: 'Oscillator 2', label: 'Oscillator 2 detune', shortLabel: 'Detune', min: -100, max: 100, defaultValue: 7, displayOffset: 0 },
  { id: 'osc2Shape', section: 'Oscillator 2', label: 'Oscillator 2 shape', shortLabel: 'Shape', min: 1, max: 99, defaultValue: 50 },
  { id: 'osc2Level', section: 'Mixer', label: 'Oscillator 2 level', shortLabel: 'Osc 2', min: 0, max: 100, defaultValue: 100 },
  { id: 'filterType', section: 'Filter 1', label: 'Oscillator 1 filter type', shortLabel: 'Type', min: 0, max: 2, defaultValue: 0, valueLabels: ['LP', 'HP', 'BP'] },
  { id: 'filterCutoff', section: 'Filter 1', label: 'Oscillator 1 filter cutoff', shortLabel: 'Cutoff', min: 100, max: 12000, defaultValue: 6000 },
  { id: 'filterResonance', section: 'Filter 1', label: 'Oscillator 1 filter resonance', shortLabel: 'Resonance', min: 0, max: 100, defaultValue: 15 },
  { id: 'filter2Type', section: 'Filter 2', label: 'Oscillator 2 filter type', shortLabel: 'Type', min: 0, max: 2, defaultValue: 0, valueLabels: ['LP', 'HP', 'BP'] },
  { id: 'filter2Cutoff', section: 'Filter 2', label: 'Oscillator 2 filter cutoff', shortLabel: 'Cutoff', min: 100, max: 12000, defaultValue: 6000 },
  { id: 'filter2Resonance', section: 'Filter 2', label: 'Oscillator 2 filter resonance', shortLabel: 'Resonance', min: 0, max: 100, defaultValue: 15 },
  { id: 'filterEnvelopeAmount', section: 'Filter', label: 'Filter envelope amount', shortLabel: 'Envelope amount', min: 0, max: 100, defaultValue: 35 },
  { id: 'ampAttack', section: 'Amp envelope', label: 'Amplifier attack', shortLabel: 'Attack', min: 0, max: 20000, defaultValue: 15 },
  { id: 'ampDecay', section: 'Amp envelope', label: 'Amplifier decay', shortLabel: 'Decay', min: 0, max: 22000, defaultValue: 350 },
  { id: 'ampSustain', section: 'Amp envelope', label: 'Amplifier sustain', shortLabel: 'Sustain', min: 0, max: 100, defaultValue: 75 },
  { id: 'ampRelease', section: 'Amp envelope', label: 'Amplifier release', shortLabel: 'Release', min: 0, max: 30000, defaultValue: 500 },
  { id: 'filterAttack', section: 'Filter envelope', label: 'Filter attack', shortLabel: 'Attack', min: 0, max: 20000, defaultValue: 10 },
  { id: 'filterDecay', section: 'Filter envelope', label: 'Filter decay', shortLabel: 'Decay', min: 0, max: 22000, defaultValue: 600 },
  { id: 'filterSustain', section: 'Filter envelope', label: 'Filter sustain', shortLabel: 'Sustain', min: 0, max: 100, defaultValue: 30 },
  { id: 'filterRelease', section: 'Filter envelope', label: 'Filter release', shortLabel: 'Release', min: 0, max: 30000, defaultValue: 500 },
  { id: 'lfoRate', section: 'LFO', label: 'LFO rate', shortLabel: 'Rate', min: 1, max: 20, defaultValue: 4 },
  { id: 'lfoPitchDepth', section: 'LFO', label: 'LFO pitch depth', shortLabel: 'Pitch depth', min: 0, max: 1200, defaultValue: 0 },
  { id: 'lfoFilterDepth', section: 'LFO', label: 'LFO cutoff depth', shortLabel: 'Cutoff depth', min: 0, max: 100, defaultValue: 0 },
  { id: 'lfoResonanceDepth', section: 'LFO', label: 'LFO resonance depth', shortLabel: 'Resonance depth', min: 0, max: 100, defaultValue: 0 },
  { id: 'polyphony', section: 'Voice / unison', label: 'Polyphony', shortLabel: 'Polyphony', min: 1, max: 16, defaultValue: 8, valueLabels: ['1 note (mono)', '2 notes', '3 notes', '4 notes', '5 notes', '6 notes', '7 notes', '8 notes', '9 notes', '10 notes', '11 notes', '12 notes', '13 notes', '14 notes', '15 notes', '16 notes'] },
  { id: 'unisonVoices', section: 'Voice / unison', label: 'Unison voices', shortLabel: 'Unison voices', min: 1, max: 4, defaultValue: 1, valueLabels: ['1 voice', '2 voices', '3 voices', '4 voices'] },
  { id: 'unisonDetune', section: 'Voice / unison', label: 'Unison detune', shortLabel: 'Spread', min: 0, max: 100, defaultValue: 15 },
] as const satisfies readonly ParameterDefinition[]

export type WebSynthParameterId = (typeof webSynthParameters)[number]['id']

export const webSynthParameterHelp = {
  osc1Shape: 'For square waves, set pulse width from 1% to 99%; 50% is a square. For other waves, shift phase around the neutral 50% position. Phase changes the alignment of oscillator harmonics, not pitch; it is most audible when mixing oscillators at matching pitches.',
  osc2Shape: 'For square waves, set pulse width from 1% to 99%; 50% is a square. For other waves, shift phase around the neutral 50% position. Phase changes the alignment of oscillator harmonics, not pitch; it is most audible when mixing oscillators at matching pitches.',
  filterType: 'Choose oscillator 1 filtering: LP (low-pass) removes frequencies above cutoff, HP (high-pass) removes frequencies below cutoff, and BP (band-pass) keeps frequencies around cutoff.',
  filter2Type: 'Choose oscillator 2 filtering independently: LP (low-pass), HP (high-pass), or BP (band-pass). Only oscillator 2 passes through this filter.',
  filter2Cutoff: 'Set oscillator 2 cutoff in hertz independently of oscillator 1. LP removes higher frequencies, HP removes lower frequencies, and BP passes a band around cutoff. The shared envelope and cutoff LFO depth move both filters relative to their own base cutoffs.',
  filter2Resonance: 'Emphasize frequencies near oscillator 2 cutoff independently of oscillator 1. The shared resonance LFO depth moves both filters relative to their own resonance settings.',
  lfoResonanceDepth: 'Modulate both filter resonances around their base values. Depth is a percentage of available headroom, so Q stays positive. Set pitch, cutoff, or resonance depth to zero to disable that assignment; multiple assignments can be active together.',
  polyphony: 'Choose the maximum number of simultaneous notes, from mono to 16. The oldest note is stolen when all slots are occupied. Changing polyphony releases sounding notes.',
  unisonVoices: 'Stack one to four copies of each oscillator per played note. Copies are symmetrically detuned using Spread, and levels are normalized to avoid a volume jump. Changing this count releases sounding notes.',
  unisonDetune: 'Set the maximum detune in cents on either side of a note for stacked unison voices. Zero aligns their tuning. With one unison voice, spread has no effect.',
  osc1Wave: 'Choose the repeating wave that generates oscillator 1 sound. A sine has only the fundamental frequency; triangle adds gentle odd harmonics, sawtooth adds odd and even harmonics, and square emphasizes odd harmonics. Harmonics are overtones that give a sound its tone color, or timbre.',
  osc2Wave: 'Choose the repeating wave that generates oscillator 2 sound. Sine is pure, triangle is mellow, sawtooth is bright, and square is hollow. Their different mixtures of harmonics (overtones) change the timbre; blending two waveforms creates richer sounds.',
  osc1Detune: 'Shift oscillator 1 pitch above or below the played note in cents. There are 100 cents in a semitone. Small tuning differences between oscillators create beating, a slow pulsing interference that can make the sound feel thicker.',
  osc2Detune: 'Shift oscillator 2 pitch above or below the played note in cents (100 cents per semitone). A small difference from oscillator 1 creates beating and a chorus-like thickness; matching their tuning gives a steadier blend.',
  osc1Level: 'Set how much oscillator 1 contributes to the mix before the filter. Mixing adds sound sources together: reduce this level to favor oscillator 2, or set it to zero to silence oscillator 1.',
  osc2Level: 'Set how much oscillator 2 contributes to the mix before the filter. Blending oscillators combines their harmonics and tuning differences. Set this level to zero to hear oscillator 1 alone.',
  filterCutoff: 'Set oscillator 1 cutoff in hertz. LP removes frequencies above cutoff, HP removes frequencies below it, and BP passes frequencies around it. The shared filter envelope and cutoff LFO depth move both filters relative to their own base cutoffs.',
  filterResonance: 'Emphasize frequencies near oscillator 1 cutoff independently of oscillator 2. Resonance adds a ringing peak. The shared resonance LFO depth moves both filters relative to their own resonance settings.',
  filterEnvelopeAmount: 'Set how far the filter envelope raises cutoff above its base value. An envelope is a one-time shape triggered by each note, unlike a repeating LFO. At zero, the filter ADSR has no effect; higher amounts create stronger changes in brightness.',
  ampAttack: 'Set attack from 0 to 20 seconds. Enter milliseconds in the numeric editor; values of 1000 ms or more display in seconds. Attack is the time for a new note to rise from silence to peak volume. Short attack is immediate; long attack fades in.',
  ampDecay: 'Set decay from 0 to 22 seconds. Enter milliseconds in the numeric editor; longer values display in seconds. Decay is the time for volume to fall from the attack peak to sustain. Short decay gives a quick drop; longer decay creates a gradual settling.',
  ampSustain: 'Set the volume held after attack and decay while the key remains pressed, as a percentage of peak volume. Sustain is a level, not a duration. Low sustain gives a fading or plucked character; high sustain keeps the note strong.',
  ampRelease: 'Set release from 0 to 30 seconds. Enter milliseconds in the numeric editor; longer values display in seconds. Release is the time for volume to fade to silence after key-up. Short release stops sharply; long release lets the sound trail off.',
  filterAttack: 'Set filter attack from 0 to 20 seconds. Enter milliseconds in the numeric editor; longer values display in seconds. Cutoff rises from its base value to the envelope peak when a note starts. Envelope amount determines how far cutoff moves.',
  filterDecay: 'Set filter decay from 0 to 22 seconds. Enter milliseconds in the numeric editor; longer values display in seconds. Cutoff falls from the envelope peak to its sustain position, letting the initial brightness settle. Envelope amount must be above zero to hear the change.',
  filterSustain: 'Set the held filter envelope position as a percentage of its excursion above base cutoff. Sustain is a level, not a time: zero returns to base cutoff, and 100 holds the envelope peak. Envelope amount determines the size of that excursion.',
  filterRelease: 'Set filter release from 0 to 30 seconds. Enter milliseconds in the numeric editor; longer values display in seconds. Cutoff returns to its base value after key-up. Its closing movement is audible only while the amplifier envelope still lets sound through.',
  lfoRate: 'Set how many cycles per second the low-frequency oscillator (LFO) repeats. An LFO modulates other controls instead of acting as an audible sound source. Slow rates create gentle movement; faster rates create rapid pitch or brightness pulsation.',
  lfoPitchDepth: 'Set the strength of the LFO pitch movement, scaled in cents (100 cents per semitone). Repeating pitch modulation creates vibrato on both oscillators. Zero leaves pitch steady; larger depths produce more pronounced wobble.',
  lfoFilterDepth: 'Set how strongly the LFO moves both filter cutoffs, as a percentage of each base cutoff. Depth is limited by available headroom above the envelope peak to keep cutoff within the audio range. Zero disables this assignment; rate controls its speed. Pitch and resonance assignments can run at the same time.',
} satisfies Record<WebSynthParameterId, string>

export const webSynthDefaultValues = Object.fromEntries(
  webSynthParameters.map((parameter) => [parameter.id, parameter.defaultValue]),
) as Record<WebSynthParameterId, number>

export const webSynthPresets = [
  {
    id: 'soft-pad',
    name: 'Soft Pad',
    values: {
      ...webSynthDefaultValues,
      osc1Wave: 1,
      osc2Wave: 2,
      osc1Level: 85,
      osc2Level: 60,
      osc2Detune: 12,
      filterCutoff: 3200,
      filterResonance: 20,
      filter2Cutoff: 3200,
      filter2Resonance: 20,
      filterEnvelopeAmount: 25,
      ampAttack: 900,
      ampDecay: 1200,
      ampSustain: 68,
      ampRelease: 1800,
      filterAttack: 700,
      filterDecay: 1400,
      filterSustain: 35,
      filterRelease: 1700,
      lfoRate: 3,
      lfoPitchDepth: 7,
      lfoFilterDepth: 12,
    },
  },
  {
    id: 'bright-lead',
    name: 'Bright Lead',
    values: {
      ...webSynthDefaultValues,
      osc1Wave: 2,
      osc2Wave: 3,
      osc1Level: 80,
      osc2Level: 55,
      osc2Detune: 5,
      filterCutoff: 7200,
      filterResonance: 32,
      filter2Cutoff: 7200,
      filter2Resonance: 32,
      filterEnvelopeAmount: 55,
      ampAttack: 5,
      ampDecay: 500,
      ampSustain: 80,
      ampRelease: 250,
      filterAttack: 0,
      filterDecay: 420,
      filterSustain: 28,
      filterRelease: 240,
      lfoRate: 6,
      lfoPitchDepth: 4,
      lfoFilterDepth: 8,
    },
  },
  {
    id: 'round-bass',
    name: 'Round Bass',
    values: {
      ...webSynthDefaultValues,
      osc1Wave: 2,
      osc2Wave: 0,
      osc1Level: 100,
      osc2Level: 45,
      osc2Detune: -12,
      filterCutoff: 950,
      filterResonance: 18,
      filter2Cutoff: 950,
      filter2Resonance: 18,
      filterEnvelopeAmount: 72,
      ampAttack: 3,
      ampDecay: 280,
      ampSustain: 82,
      ampRelease: 160,
      filterAttack: 0,
      filterDecay: 330,
      filterSustain: 8,
      filterRelease: 150,
      lfoRate: 2,
      lfoPitchDepth: 0,
      lfoFilterDepth: 4,
    },
  },
] as const satisfies readonly SynthPreset[]
